### ISSUE TITLE
faield to download rustup in WSL

### ISSUE THREAD

**Issue by binbowang1987** [drmikehenry/romt#4]
I followed the README to download rust artifacts, I successfully download the toolchain. When download rustup, there is some problem.

```shell
romt rustup -v -s stable -t linux download
```

```
Fixup: stable
[read] rustup/release-stable.toml
[read] rustup/release-stable.toml
[write] rustup/release-stable.toml (version=1.23.1)
[read] rustup/release-stable.toml
[copytree] rustup/archive/1.23.1 -> rustup/dist
Traceback (most recent call last):
  File "/home/binbowang/.local/bin/romt", line 8, in <module>
    sys.exit(main())
  File "/home/binbowang/.local/lib/python3.8/site-packages/romt/cli.py", line 164, in main
    romt.rustup.Main(args).run()
  File "/home/binbowang/.local/lib/python3.8/site-packages/romt/rustup.py", line 504, in run
    self.cmd_fixup()
  File "/home/binbowang/.local/lib/python3.8/site-packages/romt/rustup.py", line 483, in cmd_fixup
    shutil.copytree(archive_version_path, dist_path)
  File "/usr/lib/python3.8/shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.8/shutil.py", line 510, in _copytree
    raise Error(errors)
shutil.Error: [('rustup/archive/1.23.1/x86_64-unknown-linux-gnu/rustup-init', 'rustup/dist/x86_64-unknown-linux-gnu/rustup-init', '[Errno 1] Operation not permitted'), ('rustup/archive/1.23.1/x86_64-unknown-linux-gnu/rustup-init.sha256', 'rustup/dist/x86_64-unknown-linux-gnu/rustup-init.sha256', '[Errno 1] Operation not permitted'), (<DirEntry 'x86_64-unknown-linux-gnu'>, 'rustup/dist/x86_64-unknown-linux-gnu', '[Errno 1] Operation not permitted'), (PosixPath('rustup/archive/1.23.1'), PosixPath('rustup/dist'), '[Errno 1] Operation not permitted')]
```

**Comment by binbowang1987** [comment]
It does not work in mounted path. I changed to WSL inner path, and it becomes ok.

**Comment by drmikehenry** [comment]
Congratulations on figuring out the issue.  As I don't have access to Windows 10, it would have been difficult for me to reproduce this on my own system.  I'm glad it's working for you now.
